title: OpenSiege
lang: en
description: OpenSiege is an open source implementation of the game Dungeon Siege by Gas Powered Games.
repository: opensiege/opensiege.github.io

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
